spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

#  config:
#    import: application-secret.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: temp
            client-secret: temp
            scope:
              - email
              - profile

jwt:
  issuer: yejinoh58@gmail.com
  secret_key: temp

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG



