#workflow 이름 지정 (워크플로우 = CI를 실행하기 위한 스크립트 모음)
name: CI

#워크플로우가 시작될 조건 지정 (main에 push가 발생할 때 마다 워크플로우 시작)
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest #실행 환경 지정
    # 실행 스탭 지정 ( uses = 별도의 작업, run = 명령어)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Create application-secret.yml
        run: |
          cat <<EOF > src/main/resources/application-secret.yml
          jwt:
          issuer: ${{ secrets.JWT_ISSUER }}
          secret_key: ${{ secrets.JWT_SECRET_KEY }}
          
          spring:
          security:
           oauth2:
             client:
               registration:
                 google:
                   client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
                   client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                   scope:
                     - email
                     - profile
          EOF


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
